### ISSUE TITLE
Some problems with the size of input image to usemodel.py

### ISSUE THREAD

**Issue by Endauvor** [ivanpuhachov/line-drawing-vectorization-polyvector-flow#7]
For some reason prediction of keypoints doesn't work well for different resolutions of input image. For some sizes it works well, for some it doesn't work at all (I get just white output). I attached a few examples: 
1) For input 1 I get just white output 5
2) For input 3 I get output 4 (you can see some bad new details)
3) On output 2 there are some missed vertices

Could you please advice me how can to fix these bags?

![1](https://github.com/user-attachments/assets/4ebcd8d7-5b1c-472a-80c1-e714671a9ecc)
![2](https://github.com/user-attachments/assets/9e0a5e9e-98a9-4f94-baf5-664036f9865c)
![3](https://github.com/user-attachments/assets/e9547722-236f-411f-b19a-d4829bab9157)
![4](https://github.com/user-attachments/assets/7be0d34f-8fd7-402f-b08d-594f8319af1b)
![5](https://github.com/user-attachments/assets/e89170f2-c2f7-4726-9069-c13b17f62cb6)
5.png

**Comment by ivanpuhachov** [comment]
> For input 1 I get just white output 5

My best guess is that there is a problem with image encoding. If I just take a screenshot of you image and put it into the pipeline the results are as expected

Input:
![testimg](https://github.com/user-attachments/assets/dcb92e23-f6d0-42c9-9d79-36f62751ec09)

Output:
![image](https://github.com/user-attachments/assets/4685b1cf-886e-41f6-b5fe-8f788240d57f)

**Comment by ivanpuhachov** [comment]
> For some reason prediction of keypoints doesn't work well for different resolutions of input image. For some sizes it works well, for some it doesn't work at all (I get just white output)
> 2. For input 3 I get output 4 (you can see some bad new details)


Yes, the keypoint detector is not perfect. We did not augment it with possible compression artifacts. We assume that the input image is relatively clean, and the subject is in the centre of the frame.
To fix input 1 and 3 please check the input processing part, I believe you need to modify `png_to_numpy()` in `sketchyimage.py`. As I mentioned above, the problem might simply be in image encoding.

 > 3. On output 2 there are some missed vertices

For output 2, "missing" keypoints are ambiguous - our pipeline naturally resolves y-junctions (smooth connections) and we did not require these points to be detected. We show the results of our vectorization on this input on Fig. 15. 
If you absolutely need those points detected I guess the only option is to retrain the detector.
